### ISSUE TITLE
Thanks! 

### ISSUE THREAD

**Issue by davewatson91** [madpilot/hass-amber-electric#1]
Until I can work out how to fork a fork which is a different fork of the same fork I already have..... 

Step 2 of installation instructions points to https://api.amber.com.au/developers

I believe it should be https://app.amber.com.au/developers/

Thanks for all your work!

**Comment by madpilot** [comment]
I've removed the fork link, so you can probably just fork off this. I'll fix up the README.

**Comment by madpilot** [comment]
Link updated.
