### ISSUE TITLE
No entities showing on the Integration screen

### ISSUE THREAD

**Issue by gorillica** [madpilot/hass-amber-electric#10]
Hi Myles, great work!

I’ve installed your component, and have gone through the config flow. I’ve picked the one site accessible on my account, named it, and then I get an empty integration, with no entities added. I’ve repeated this several times, always with the same effect. Am I missing something really obvious?

I began to play with the API using the same key and got data fed back to me in my API playground, so I’m not sure what’s happening. Oh, and I have got ‘automatically add entities’ turned on for the integration!

**Comment by madpilot** [comment]
What did you name it? Is there anything in your logs?

Can you turn in debug mode and then try re-adding it?

**Comment by madpilot** [comment]
And what version of HASS are you running? The integration needs a recent one (I want to get it in core so I need to track the latest version)

**Comment by gorillica** [comment]
> What did you name it?
 
I've tried two names: ‘Home’ and the name of my suburb.

> Can you turn in debug mode and then try re-adding it?

I turned on debug logging for the component. A little while after restarting (with just the original integration still installed) I got a message about data which had been retrieved from the Amber API:

```
2021-06-23 10:48:18 DEBUG (SyncWorker_0) [custom_components.amberelectric] Fetched new Amber data: [{'duration': 30.0, 'spot_per_kwh': 9.537, 'per_kwh': 22.17544, 'date': datetime.date(2021, 6, 22), 'nem_time': datetime.datetime(2021, 6, 22, 0, 30, tzinfo=tzoffset(None, 36000)), 'start_time': datetime.datetime(2021, 6, 21, 4, 0, 1, tzinfo=tzutc()), 'end_time': datetime.datetime(2021, 6, 21, 4, 30, tzinfo=tzutc()), 'renewables': 7.1716940319726845, 'channel_type': <ChannelType.GENERAL: 'general'>, 'spike_status': <SpikeStatus.NO_SPIKE: 'none'>, 'type': 'ActualInterval'}, {'duration': 30.0, 'spot_per_kwh': 7.263300000000001, 'per_kwh': 19.771, 'date': datetime.date(2021, 6, 22), 'nem_time': datetime.datetime(2021, 6, 22, 1, 0, tzinfo=tzoffset(None, 36000)), 'start_time': datetime.datetime(2021, 6, 21, 4, 30, 1, tzinfo=tzutc()), 'end_time': datetime.datetime(2021, 6, 21, 5, 0, tzinfo=tzutc()),…
```

I'm not pasting the whole thing here, but it goes on and on. This then gets repeated every couple of minutes or so, followed by

```
2021-06-23 10:48:19 DEBUG (MainThread) [custom_components.amberelectric] Finished fetching amberelectric data in 2.210 seconds
```

I then tried adding a second instance of the integration. I went through the config flow again (with a different name for identification: just ‘Home’ now rather than the suburb!), and haven't seen anything in the logs relating to the config flow

> And what version of HASS are you running? The integration needs a recent one (I want to get it in core so I need to track the latest version)

I'm on 2021.6.5, running in Docker.

**Comment by madpilot** [comment]
That all looks fine. Have you removed the old component and removed the entry from the config?

**Comment by gorillica** [comment]
I didn't at first, but I did remove the old stuff (and try deleting and reinstalling the new component/integration) before opening this issue.

**Comment by madpilot** [comment]
Ok, I've got a couple of ideas, I'll try out tomorrow.

Sorry about that!

**Comment by gorillica** [comment]
No need to apologize! Thanks for everything.

**Comment by darren365** [comment]
Following this issue as am experiencing the same. No devices showing. When originally installed I was a couple of minor versions behind in OS and Core, have updated everything and tried again with same outcome. After obtaining the API Token and adding it during the setup prompt, used the dropdown to select my only option. Named it grasslands.
![image](https://user-images.githubusercontent.com/17172663/123243136-e22a6b80-d521-11eb-89c0-0aa561e207ff.png)

**Comment by madpilot** [comment]
Ok, thanks for the report. I'll release a version with additional logging tomorrow (I didn't get a chance to do that today).

Are you on docker too? And did you uninstall the old integration before installing the new one?

**Comment by darren365** [comment]
@madpilot Thanks for reply. I renamed my existing amberelectric within the custom_components folder to amberelectricold prior to copying across the new one, but forgot to comment out the applicable sensor sections in configuration.yaml, noticed this after a reboot so did make changes after. Have deleted and reinstalled since then. After first setup thought I should update everything I could update so did that after first install too.

**Comment by madpilot** [comment]
Ok, maybe having the config there to start with had messed up the internal database. At least that gives me another thing to check.

Thanks for the extra info!

**Comment by madpilot** [comment]
Can you both do me a favour?

Open `.storage/core.config_entries` and find _any_ thing that has amber in it (Don't post your api_token)

**Comment by gorillica** [comment]
Sure! I've got two entries, right at the end of the `core.config_entries` file:

```
            {
                "entry_id": "9c9c02a672f6ef9f889d55d156405191",
                "version": 1,
                "domain": "amberelectric",
                "title": "[Suburb]",
                "data": {
                    "site_id": "xxx",
                    "api_token": "***",
                    "site_nmi": "NMI"
                },
                "options": {},
                "pref_disable_new_entities": false,
                "pref_disable_polling": false,
                "source": "user",
                "unique_id": null,
                "disabled_by": null
            },
            {
                "entry_id": "xxx",
                "version": 1,
                "domain": "amberelectric",
                "title": "Home",
                "data": {
                    "site_id": "01F4V8F4EKZ071T39BCNZQBPJR",
                    "api_token": "***",
                    "site_nmi": "NMI"
                },
                "options": {},
                "pref_disable_new_entities": false,
                "pref_disable_polling": false,
                "source": "user",
                "unique_id": null,
                "disabled_by": null
            }

```

Nothing else in `core.config_entries` has ‘amber’ in it.

**Comment by darren365** [comment]
Just one Amber entry.
            {
                "entry_id": "f99a0f6dabf032caaf2f5b6b41dfe30c",
                "version": 1,
                "domain": "amberelectric",
                "title": "Grasslands",
                "data": {
                    "site_id": "01EZB768MNK7SZ4E871JDBSJ8Q",
                    "api_token": "removed",
                    "site_nmi": "2001180811"
                },
                "options": {},
                "pref_disable_new_entities": false,
                "pref_disable_polling": false,
                "source": "user",
                "unique_id": null,
                "disabled_by": null
            }

**Comment by madpilot** [comment]
I tried with the old plugin installed, and I can't get it to fail, so now let's try annoying debug message mode.

I just pushed an update with some more debug messages. If you enable debugging, you should see:

```
2021-06-26 09:47:02 DEBUG (MainThread) [custom_components.amberelectric] Finished fetching amberelectric data in 1.229 seconds
2021-06-26 09:47:02 DEBUG (MainThread) [custom_components.amberelectric] Fetch complete. Adding entities...
2021-06-26 09:47:02 DEBUG (MainThread) [custom_components.amberelectric] Adding 6 sensors
2021-06-26 09:47:02 DEBUG (MainThread) [custom_components.amberelectric] Entry setup complete.
```

Or similar.

IF you can send me all the messages from `custom_components.amberelectric` that would be awesome.

**Comment by gorillica** [comment]
I will do that shortly. But first, I realized as I was about to go to bed last night that the entities *had* in fact been added. I'm a doofus! They just aren’t appearing as part of the integration. But I have got `sensor.home_general_forecast`, `sensor.home_general_price`, `sensor.home_price_spike`, and `sensor.home_renewables` (and equivalent sensors for the suburb-named installation)…

**Comment by madpilot** [comment]
Ahh! Yeah, it doesn't show up yet

![image](https://user-images.githubusercontent.com/19585/123495431-0a6fb280-d667-11eb-8431-018cd96eb479.png)

Sounds like it's working as expected.

It will eventually show up on the integration page

**Comment by gorillica** [comment]
I'm so sorry for all the trouble! Thanks, Myles!

**Comment by darren365** [comment]
Damn, sorry to mess you around @madpilot. Outcome is same for me too, there are sensors listed using the name "Grasslands" that I gave. I did search for sensors but was searching using phrase of "Amber". Thanks for looking at this, look forward to getting the automation pieces going again now.

**Comment by madpilot** [comment]
I need to be sorry - this is a legit UX bug, so I'll leave it open

**Comment by madpilot** [comment]
If you update to the latest version, the entity count will be there now

![image](https://user-images.githubusercontent.com/19585/125633570-2a065efa-7e38-4afa-a7c0-a736cf9984eb.png)

**Comment by gorillica** [comment]
Thanks, Myles!
