### ISSUE TITLE
Price Spike State not changing

### ISSUE THREAD

**Issue by chiefcomm** [madpilot/hass-amber-electric#12]
Hi Myles,

Just uncovered this you may already be aware but I couldn't find it mentioned in any closed or open issue.

The price spike sensor is not showing any status other than False which may be a bug.

![image](https://user-images.githubusercontent.com/45157523/123920792-aaac3b00-d9c9-11eb-927f-d13412a56dcc.png)

**Comment by madpilot** [comment]
We haven't had any price spikes since the 21 June, which was before this component was released. The spike sensor is a binary sensor, so it'll only go true when a spike occurs (it doesn't change on a potential spike)

**Comment by madpilot** [comment]
Not to say it _is_ working, we just haven't see it yet 😃

**Comment by chiefcomm** [comment]
Thanks Myles, I thought it was correlating to the "Custom Price Notifications" in the Android/iOS App.
What will constitute a spike?
Thanks for clarifying :-)

**Comment by madpilot** [comment]
Our definition of a spike: at least one 5 minute actual in the 30 minute period over $3 AND the weighted average of the 30 minutes period is over $3

**Comment by chiefcomm** [comment]
Thanks Myles

**Comment by chiefcomm** [comment]
Thanks Myles
