### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by shubu000** [madpilot/hass-amber-electric#16]
hi, 
sorry to be a bother, i tried to install the custom component as per instruction.

i have copied it into my customer component folder

shubu@sparez:/usr/share/hassio/homeassistant/custom_components$ ls -lart
total 84
drwxr-xr-x  4 root root  4096 Jun 14  2020 smartir
drwxr-xr-x  3 root root  4096 Jan  2  2021 fronius_inverter
drwxr-xr-x  2 root root  4096 Feb  5 15:07 entity_controller
drwxr-xr-x  5 root root  4096 Jun  3 23:09 bureau_of_meteorology
drwxr-xr-x 12 root root  4096 Jul  3 16:14 hacs
drwxr-xr-x  3 root root  4096 Jul 17 20:45 amberelectric
drwxr-xr-x 12 root root  4096 Jul 17 20:50 .
drwxr-xr-x  4 root root  4096 Jul 17 20:50 public_transport_victoria
drwxr-xr-x 12 root root  4096 Jul 17 20:54 ..
shubu@sparez:/usr/share/hassio/homeassistant/custom_components/amberelectric$ ls -lart
total 48
-rw-r--r--  1 root root  3827 Jul 17 20:45 config_flow.py
-rw-r--r--  1 root root   346 Jul 17 20:45 __init__.py
-rw-r--r--  1 root root   192 Jul 17 20:45 const.py
-rw-r--r--  1 root root   416 Jul 17 20:45 manifest.json
-rw-r--r--  1 root root  4871 Jul 17 20:45 coordinator.py
-rw-r--r--  1 root root 11633 Jul 17 20:45 sensor.py
drwxr-xr-x  2 root root  4096 Jul 17 20:45 translations
drwxr-xr-x  3 root root  4096 Jul 17 20:45 .
drwxr-xr-x 12 root root  4096 Jul 17 20:50 ..

however i have managed to restart the server twice but i still can't see it
![amber HACs](https://user-images.githubusercontent.com/7950320/126034863-56516c07-99b6-40d2-9d13-7145ab5341e2.png)
i had tried to install it from HACs as well but that didn't work either

i am running a supervised hassio docker container

after adding the module into the config.yml i can see the amber icon in the integration list, but i cna't configure it nor add it as per the instructions..

any help would be greatly appreciated

this is my info page
## System Health

version | core-2021.7.3
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.9.5
os_name | Linux
os_version | 4.19.0-16-amd64
arch | x86_64
timezone | Australia/Melbourne

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4753
Installed Version | 1.13.2
Stage | running
Available Repositories | 911
Installed Repositories | 9

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 10 (buster)
-- | --
update_channel | stable
supervisor_version | supervisor-2021.06.8
docker_version | 20.10.5
disk_total | 65.1 GB
disk_used | 26.7 GB
healthy | true
supported | true
supervisor_api | ok
version_api | ok
installed_addons | Visual Studio Code (3.6.0), Duck DNS (1.12.5), Mosquitto broker (6.0.1), NGINX Home Assistant SSL proxy (3.0.1), Zigbee2mqtt (1.18.1-1), Terminal & SSH (9.1.3)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 3
views | 2
mode | storage

</details>

**Comment by madpilot** [comment]
Is there anything in the log file?

**Comment by madpilot** [comment]
And did you copy the contents on the translations folder?

**Comment by shubu000** [comment]
sorry Madpilot, which logs would you need? hassio?

as for the translations folder i have this

root@sparez:/usr/share/hassio/homeassistant/custom_components/amberelectric/translations# ls -lart
total 12
drwxr-xr-x 2 root root 4096 Jul 17 20:45 .
-rw-r--r-- 1 root root  866 Jul 17 20:45 en.json
drwxr-xr-x 4 root root 4096 Jul 17 20:57 ..
root@sparez:/usr/share/hassio/homeassistant/custom_components/amberelectric/translations#

**Comment by madpilot** [comment]
There should be a Logs button in the configuration section. Look for any errors or warnings from amberelectric

**Comment by shubu000** [comment]
i don't know what happened but it's OK now
sorry to bother you
i don't know if there was anything other than me restarting it a bunch of times to get remote access working
thanks for your patience

**Comment by madpilot** [comment]
Were you refreshing the integrations page between restarts? I found that it doesn't auto refresh.
