### ISSUE TITLE
No way to register for Amber API token now

### ISSUE THREAD

**Issue by tmugan** [madpilot/hass-amber-electric#25]
Following the steps to enable the link https://app.amber.com.au/developers does not provide a link to register API tokens.  Is this link no longer valid or have Amber stopped issuing new tokens to developers?

**Comment by OmgImAlexis** [comment]
Are you signed in? There should be a big button.

![image](https://user-images.githubusercontent.com/6525926/132439142-9f69756e-7e8c-451d-acb1-39a223f1adf3.png)

**Comment by OmgImAlexis** [comment]
Also make sure to goto https://app.amber.com.au/settings/ and enable developer mode.

**Comment by madpilot** [comment]
Yep, bang on @OmgImAlexis 

(You can also enable it on the developer page using the slider on the top right)

**Comment by tmugan** [comment]
Thanks. I presumed I needed to create a separate developer account here.
