### ISSUE TITLE
Unit of measurements out of sync between state and forecast device attribute

### ISSUE THREAD

**Issue by mindmelting** [madpilot/hass-amber-electric#27]
First off great work getting this updated to work with the Energy dashboard!

Since the latest update, I have noticed that on the `AmberForecastSensor` the native value is returning $/kWh and the forecasts that are returned in the device state attributes are still returning c/kWh - which makes it a little inconsistent. I think there are other values throughout the sensors that are still c/kWh too.

https://github.com/madpilot/hass-amber-electric/blob/master/custom_components/amberelectric/sensor.py#L126
https://github.com/madpilot/hass-amber-electric/blob/master/custom_components/amberelectric/sensor.py#L149

Seems to be the same in the home assistant `core` repository too.

Happy to raise a PR if this should be changed - let me know!

**Comment by madpilot** [comment]
Great point - A PR would be good - but over on `home-assistant/core` (This repo is only here as an archive)

**Comment by madpilot** [comment]
(If you aren't setup for that, let me know - I can do it)

**Comment by mindmelting** [comment]
Yep - let me do that later today!

**Comment by madpilot** [comment]
Thanks!

**Comment by mindmelting** [comment]
@madpilot quick one - what do `range_min` and `range_max` represent - should they also be converted? (They don't come back in my local instance, and you probably know this off by heart!)

https://github.com/madpilot/hass-amber-electric/blob/master/custom_components/amberelectric/sensor.py#L159

**Comment by madpilot** [comment]
They are the min and max price from the AEMO prediction engine. They should be converted

**Comment by mindmelting** [comment]
After taking an age to set up all the requirements for `core` here you go:

https://github.com/home-assistant/core/pull/57109

**Comment by madpilot** [comment]
Yeah, it takes a while.

I really appreciate it! Thank you!

**Comment by mindmelting** [comment]
By the way I created a new integration for Powerpal devices: https://github.com/mindmelting/hass-powerpal combining it with your Amber integration on the Energy dashboard gives pretty accurate pricing (within a cent or two) over the course of a day

**Comment by madpilot** [comment]
Nice one! I've been using the Eagle 200 to the same end. It's a couple of cents out. I _think_ it's to do with when HA downloads prices.

I'm also working with these devs to allow us to import history pricing data, which may fix that.
