### ISSUE TITLE
Question regarding Energy Monitor w.r.t. Amber real time pricing

### ISSUE THREAD

**Issue by chiefcomm** [madpilot/hass-amber-electric#28]
Team, what Amber sensor do you all use to provide pricing to Home Assistant?

I do not have real time pricing coming into the Energy dashboard consequently my price is always $0.

**Energy Dashboard :**
![image](https://user-images.githubusercontent.com/45157523/139353038-bc1aca8d-5c5b-4abc-a2fc-8d3029fa0865.png)
**Sensor configuration details :**
![image](https://user-images.githubusercontent.com/45157523/139353153-baadd35d-bed0-4526-9c2e-24ffe054c932.png)

**Comment by madpilot** [comment]
That's the right one, but if you don't have real-time usage data coming through, I don't _think_ the stats plugin can marry them together properly.

Where are you pulling your usage from?

**Comment by chiefcomm** [comment]
Hey @madpilot I have a 6 channel Circuit Setup with clamps on all three phases measuring real time usage.   It is working as I can see the usage real time.  Gives me something to investigate further.  Thanks heaps.

**Comment by chiefcomm** [comment]
Like always Myles you have legendary advice :-) My system is polling every 10seconds.  There is a great thread https://community.home-assistant.io/t/energy-management-cost-compensation-not-showing/329987/40 which may be the pointer for me.  Thanks again @madpilot

**Comment by madpilot** [comment]
Hopefully it helps! Good luck.
