### ISSUE TITLE
Not Working in HA anymore

### ISSUE THREAD

**Issue by shane-peiris** [madpilot/hass-amber-electric#29]
Logger: homeassistant.config_entries
Source: custom_components/amberelectric/__init__.py:22 
Integration: amberelectric 
First occurred: May 4, 2023 at 1:55:05 PM (6 occurrences) 
Last logged: 3:13:25 AM

Error setting up entry Home for amberelectric
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/amberelectric/__init__.py", line 22, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by madpilot** [comment]
This is integrated into mainline Home Assistant now.

No need to use this custom component.

**Comment by shane-peiris** [comment]
It is the same issue in the mainline HA as well

**Comment by madpilot** [comment]
Please post a bug there - if it's a breaking change and they missed updating an entity, they'll want to know.

What version number of HA are you running?

**Comment by shane-peiris** [comment]
Could you please provide me the repo link where I should post this issue?

Home Assistant 2023.5.0
Supervisor 2023.04.1
Operating System 10.1
Frontend 20230503.1 - latest

**Comment by madpilot** [comment]
https://github.com/home-assistant/core

**Comment by billhoz** [comment]
FWIW my HA/Amber is working fine

Home Assistant 2023.5.1 (just finished upgrade
Supervisor 2023.04.1
Operating System 10.1
Frontend 20230503.1 - latest
