### ISSUE TITLE
Amber api and home assit not working?

### ISSUE THREAD

**Issue by home-rj** [madpilot/hass-amber-electric#30]
I cant setup my amber account. 

Ive tried multitple times but unsure how or why it wont load considering ive done everything step by step?

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/amberelectric/__init__.py:22
Integration: amberelectric
First occurred: 9:36:16 PM (1 occurrences)
Last logged: 9:36:16 PM

Error setting up entry for amberelectric
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/amberelectric/__init__.py", line 22, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by madpilot** [comment]
There is now an offical integration in home assistant - use that, not this one.

**Comment by home-rj** [comment]
I have tried both and both are the same result, is there another option?

**Comment by madpilot** [comment]
Did you delete the custom component and restart? Custom components take precedence.

**Comment by home-rj** [comment]
Yes, i have removed the Hacs intergration. When i search on the standard store it says error
invalid api. there is no invalid api as ive copied it straght from the developers page as it says.

**Comment by madpilot** [comment]
Email info@amber.com.au (Attn: Myles) - I need to look at your account, and I don't want to do that in public.
