### ISSUE TITLE
Plans for HACS? 

### ISSUE THREAD

**Issue by davewatson91** [madpilot/hass-amber-electric#7]
Not that I imagine there will be bulk updates, but allows for nice easy installation / update paths for users... 

Just a thought 👍🏼 appreciate everything you've done so far - it's brilliant.

**Comment by madpilot** [comment]
Probably not - I'm planning on getting this in to core relatively quickly, which makes a HACS version redundant (and possibly confusing).

**Comment by davewatson91** [comment]
Even better - thanks again mate :)
