### ISSUE TITLE
Forecast value

### ISSUE THREAD

**Issue by davewatson91** [madpilot/hass-amber-electric#8]
Just playing with the forecasts. 

Have got them in, and working ok - but it appears the API is only providing a range, and not actually the value itself... 

Example for the next period, I have 8.52c range_min & 1393.38c range_max. I can average these, but they distort the numbers. 

The app itself is showing a flat 20c forecast for the same period. The API reports the spot price of 14c

Not sure how to handle this, or actually what the best course is (I'm not sure how the app determines the forecast from the range). 

Thanks!

**Comment by madpilot** [comment]
I suspect I forgot to add the `perKWH` field to the attributes. I'll sort that out shortly

**Comment by madpilot** [comment]
Yep. That was it. Fixed.
