### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by nerfherder** [madpilot/hass-amber-electric#9]
Hey - looks like you have made some great progress.

Struggling to get this to show up in my integrations, I have cloned amberelectric/ into custom_components. Are there any changes required to configuration.yaml to bring it in to my Hassio?

**Comment by nerfherder** [comment]
Figured it out - requires a new line
amberelectric:
to be added to configuration.yaml

**Comment by madpilot** [comment]
You can actually remove it completely - The component uses config flow.

Go to Integrations > Add integration > Search for Amber and Click install
